services:
  mongodb:
    image: mongo  
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern-network
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - "8081:8081"
    networks:
      - mern-network
    depends_on:
      - mongodb

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase
    networks:
      - mern-network
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: frontend 
    networks:
      - mern-network
    depends_on:
      - backend

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mern-network
    depends_on:
      - frontend

volumes:
  mongodb_data:
    driver: local

networks:
  mern-network:
    driver: bridge